version: '{build}'
image: Visual Studio 2022
configuration: Release
platform: Any CPU
install:
- cmd: git submodule update --init --recursive
before_build:
- cmd: appveyor-retry nuget restore
build:
  project: ExtremeDumper.sln
  verbosity: normal
after_build:
- cmd: 7z a bin\Release\ExtremeDumper.zip bin\Release\*.exe
artifacts:
- path: bin\Release\ExtremeDumper.zip
  name: ExtremeDumper
deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: ExtremeDumper
  auth_token:
    secure: +8UJ1C312inNq+80I8WST34vPMrCylnmTx+9rmuIh1qnsArA5x2b8yc+kcwkXmQC
  on:
    APPVEYOR_REPO_TAG: true